# !/usr/bin/python
# -*- coding: utf-8 -*-
"""
    sxw 2017-02-14

    url和方法匹配操作内容
"""

url_method_operation_mapping = [
    [r"/catalog/vpcs",
     {"POST": "列出vpc列表", "DELETE": "删除vpc信息"}],
    [r"/catalog/vpc/check-name", {"POST": "校验vpc名字是否可用"}],
    [r"/catalog/vpc", {"POST": "网络->VPC->管理员创建vpc"}],
    [r"/catalog/vpc/(\d)+",
     {"DELETE": "创建vpc", "PUT": "修改vpc信息", "GET": "获取vpc信息"}],
    [r"/catalog/vpc/tenant/select", {"POST": "租户资源池下列出VPC"}],
    [r"/catalog/subnet/tenant/subnet", {"POST": "租户创建openstack类VPC子网"}],
    [r"/catalog/subnet/tenant/subnet/(\d)+",
     {"DELETE": "租户删除vpc子网", "PUT": "租户修改vpc子网", "GET": "租户查询子网信息"}],
    [r"/catalog/subnet/tenant/subnets", {"DELETE": "租户多项删除vpc子网"}],
    [r"/catalog/subnet/tenant/vmware/subnet", {"POST": "租户创建vmware类VPC子网"}],
    [r"/catalog/subnet/tenant/subnet/list", {"POST": "租户列出子网信息"}],
    [r"/catalog/subnet/user/subnet/(\d)+",
     {"PUT": "用户修改vpc子网", "GET": "用户查询vpc子网信息"}],
    [r"/catalog/subnet/check-name", {"POST": "校验子网名称是否可用"}],
    [r"/catalog/subnet/tenant/subnet/list/(\d)+", {"POST": "获取vpc下子网列表"}],
    [r"/catalog/subnet/tenant/vpc/subnet/list/(\d)+", {"POST": "获取vpc下子网列表"}],
    [r"/catalog/subnet/vmware/chose-ip-segment", {"POST": "分配vmware可用网段"}],
    [r"/catalog/subnet/vpc/(\d)+/check-name", {"POST": "同一vpc下校验子网名称是否可用"}],
    [r"/catalog/subnet/vpc/(\d)+/check-segment", {"POST": "同一vpc下校验子网网段是否重复"}],
    [r"/catalog/subnet/tenant/recycle/subnets", {"DELETE": "删除回收站中vpc子网信息", "PUT": "恢复回收站中vpc子网"}],
    [r"/log/admin/logs", {"POST": "管理员查询用户操作日志"}],
    [r"/log/tenant/export/logs", {"POST": "租户导出用户操作日志"}],
    [r"/log/tenant/logs", {"POST": "租户查询用户操作日志"}],
    [r"/log/user/export/logs", {"POST": "导出用户操作日志"}],
    [r"/log/user/logs", {"POST": "查询用户操作日志"}],

    [r"/app/network/internetip/cmdb", {"POST": "创建公网IP", "GET": "是否可删除公网IP", "DELETE": "删除公网IP"}],
    [r"/app/network/internetip/operate", {"POST": "修改公网IP信息", "PUT": "公网IP列表"}],
    [r"/api/network/internetip/user", {"POST": "可用公网IP"}],
    [r"/app/network/ip/cmdbip", {"POST": "创建内网IP", "PUT": "是否可删除内网IP段", "DELETE": "删除内网IP段"}],
    [r"/app/network/ip/cmdbsegment", {"POST": "内网IP段列表", "GET": "内网IP段下的IP列表"}],
    [r"/api/network/vpn/index", {"POST": "创建VPN", "PUT": "创建VPN策略", "DELETE": "删除VPN策略"}],
    [r"/app/network/loadbalance/f5cluster", {"GET": "获取F5集群信息"}],
    [r"/api/network/internetip/net", {"POST": "绑定公网IP", "DELETE": "解绑公网IP", "PUT": "修改绑定的公网IP"}],

    [r"/catalog/backup_policy/index",
     {"POST": "添加备份策略", "PUT": "修改备份策略", "GET": "查看备份策略详情"}],
    [r"/catalog/backup_policy/list",
     {"POST": "高级查询和查看列表", "GET": "备份还原下拉列表"}],
    [r"/catalog/backup_policy/restore",
     {"POST": "查看没有备份主机列表", "GET": "备份还原"}],
    [r"/catalog/recycle_policy/index",
     {"POST": "修改状态", "PUT": "删除回收站策略"}],
    [r"/catalog/recycle_policy/list",
     {"POST": "添加回收策略", "PUT": "查询列表及详情", "GET": "查询已添加回收策略对象"}],
    [r"/catalog/volume/index",
     {"POST": "创建卷"}],
    [r"/catalog/vpn/list",
     {"PUT": "查询vpn列表详情及高级检索"}],
    [r"/security/member/index",
     {"GET": "查看服务列表详情"}],
    [r"/security/member/list",
     {"POST": "查看安全服务列表", "PUT": "服务设置"}],

    [r"/catalog/public_ip/index",
     {"DELETE": "公网ip进回收站", "PUT": "还原公网ip", "GET": "查看租户下的公网ip列表"}],
    [r"/catalog/public_ip/remove",
     {"DELETE": "解除租户与公网ip的绑定"}],
    [r"/catalog/bigeye_policy/bigeye_policy",
     {"PUT": "修改监控参数", "GET": "获取监控参数"}],
    [r"/management/zone/zone",
     {"POST": "增加zone", "PUT": "修改zone名称地点", "GET": "获取zone列表", "DELETE": "删除zone"}],
    [r"/management/zone/updatezone",
     {"PUT": "修改zone状态"}],
    [r"/management/zone/enable_zone",
     {"GET": "查询可用zone"}],
    [r"/management/config/vmconfig",
     {"GET": "查询虚机关联flavor列表", "POST": "虚机offering关联flavor", "PUT": "发布或取消发布虚机或物理机配置"}],
    [r"/management/config/env",
     {"GET": "查询未关联的env"}],
    [r"/management/config/flavor",
     {"GET": "查询flavor根据env_id"}],
    [r"/management/config/enablevm",
     {"GET": "查询可用虚机配置"}],
    [r"/management/config/enablepm",
     {"GET": " 查询可用物理机配置"}],
    [r"/management/config/pmconfig",
     {"GET": " 查询所有物理机配置"}],
    [r"/management/config/flavor_offering",
     {"GET": " 查询env通过offeringID", "PUT": "发布或取消发布虚机或物理机配置"}],
    [r"/management/image/image",
     {"GET": " 查询镜像根据系统类型", "POST": "注册镜像,关联模板",
      "PUT": "发布，取消发布镜像", "DELETE": "删除镜像及与模板关系"}],
    [r"/management/image/image",
     {"GET": " 查询可用物理机配置"}],
    [r"/management/image/image_environment",
     {"GET": " 查询环境,去除已经关联的环境"}],
    [r"/management/image/image_template",
     {"GET": " 查询环境对应的模板", "PUT": "取消关联根据模板id和镜像id", "POST": "镜像关联模板"}],
    [r"/management/image/image_os",
     {"GET": " 查询系统类型", "PUT": "修改镜像名称"}],
    [r"/management/image/image_environment_template",
     {"GET": " 通过镜像id查询环境模板列表"}],
    [r"/management/logicpool/logicpool",
     {"GET": " 查询客户资源池列表", "PUT": "修改客户资源池信息",
      "POST": "创建资源池", "DELETE": "删除资源池（检查资源池下是否有租户,暂未开通）"}],
    [r"/management/logicpool/pool_status",
     {"PUT": "修改客户资源池状态"}],
    [r"/management/logicpool/cluster",
     {"GET": " 查询VCenter，data center,cluster树形结构,查询env,az"}],
    [r"/management/logicpool/pool_tenant",
     {"GET": " 根据租户id查询客户资源池信息", "POST": "创建租户和客户资源池关联(指添加关联关系，未用)"}],
    [r"/management/tenant/tenant_resource",
     {"GET": " 查询客户资源池列表", "POST": "租户资源管理（绑定公网IP，创建VPC，关联资源池，添加安全服务列表，创建vpn）"}],
    [r"/management/tenant/tenant_list",
     {"POST": "查询所有租户及租户关联的资源详情列表"}],
    [r"/management/tenant/zone_pool",
     {"GET": " 查询zone下面的资源池列表（独享已分配的除外）"}],
    [r"/management/tenant/security_list",
     {"GET": " 查询全部的安全服务列表"}],
    [r"/management/tenant/tenant_security",
     {"GET": " 根据租户ID查询租户下的安全服务项"}],
    [r"/order/list",
     {"POST": "查询我的订单列表及高级搜索（含权限）"}],
    [r"/order/log",
     {"POST": "订单重做", "GET": "查看订单日志"}],
    [r"/order/details",
     {"POST": "查看订单详情"}],
    [r"/catalog/public_ip/public_ip",
     {"GET": "查看租户下的公网ip地址,去除已绑定和绑定中的"}],
    [r"/catalog/public_ip/object",
     {"GET": "查看租户下的虚机物理机负载均衡，公网ip的绑定对象"}],
    [r"/catalog/public_ip/bound",
     {"DELETE": "公网ip解绑", "PUT": "修改NAT绑定信息", "POST": "公网ip的NAT绑定"}],

    [r"/catalog/pyhsical_cluster/disk/add",
     {"POST": "集群扩容"}],
    [r"/catalog/pyhsical_cluster/cluster/list",
     {"POST": "集群列表", "PUT": "修改集群磁盘组"}],
    [r"/catalog/pyhsical_cluster/pm/list",
     {"POST": "物理机列表", "PUT": "修改物理机"}],
    [r"/catalog/pyhsical_cluster/cluster/create",
     {"POST": "创建物理机集群"}],
    [r"/catalog/pyhsical_cluster/pm/create",
     {"POST": "创建物理机"}],

    [r"/catalog/vm/create", {"POST": "创建虚机"}],
    [r"/catalog/vm/action", {"POST": "虚机启停重启操作"}],
    [r"/catalog/vm/delete", {"POST": "虚机删除操作"}],
    [r"/catalog/vm/recover", {"POST": "虚机恢复"}],
    [r"/catalog/vm/remove", {"POST": "虚机移入回收站"}],
    [r"/catalog/vm/offering", {"GET": "获取虚机配置信息"}],
    [r"/catalog/vm/template", {"GET": "获取虚机模板信息"}],
    [r"/catalog/vm/update/info", {"POST": "更新虚机信息"}],
    [r"/catalog/vm/list", {"GET": "获取虚机列表信息"}],

    [r"/catalog/f5/test", {"POST": "创建负载均衡"}],
    [r"/catalog/f5/get_resource", {"GET": "获取逻辑服务器列表"}],
    [r"/catalog/f5/list", {"POST": "获取当前租户下的负载均衡列表"}],
    [r"/catalog/f5/deletef5", {"POST": "删除负载均衡策略"}],
    [r"/catalog/fw/test", {"POST": "创建防火墙"}],
    [r"/catalog/fw/get_resource", {"GET": "获取逻辑服务器列表"}],
    [r"/catalog/fw/list", {"POST": "获取当前租户下的火墙列表"}],
    [r"/catalog/fw/deletefw", {"POST": "删除火墙策略"}],

    [r"/app/catalog/trusteeship/yes", {"POST": "查询该用户所有托管运维的机器信息"}],
    [r"/app/catalog/trusteeship/no", {"POST": "查询该用户所有自运维的机器信息"}],
]
